{% set version = "0.8.3" %}

package:
  name: nbserverproxy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbserverproxy/nbserverproxy-{{ version }}.tar.gz
  sha256: c2e7c44ce042e1892fd2b2fb75c781080393c84503e68041a9269a5b45291353

build:
  number: 0
  skip: True  # [py2k]
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - notebook

test:
  imports:
    - nbserverproxy

about:
  home: https://github.com/jupyterhub/nbserverproxy
  license: BSD 3-Clause
  license_family: BSD
#  license_file: LICENSE
  summary: Jupyter server extension to proxy web services

extra:
  recipe-maintainers:
    - ocefpaf
    - lsetiawan
