{% set version = "0.8.5" %}

package:
  name: nbserverproxy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbserverproxy/nbserverproxy-{{ version }}.tar.gz
  sha256: 38e420a8a59a402155a95ace013be5c02442efdf27c8a6e10c8ccd058b451057

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - notebook

test:
  imports:
    - nbserverproxy

about:
  home: https://github.com/jupyterhub/nbserverproxy
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Jupyter server extension to proxy web services

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
    - lsetiawan
