{% set version = "0.8.6" %}

package:
  name: nbserverproxy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nbserverproxy/nbserverproxy-{{ version }}.tar.gz
  sha256: 39843d3cdf0ab619110bd4a7ee5fd7b4157ca1bae6a28873ade493da8a2db4cf

build:
  number: 1000
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - notebook

test:
  imports:
    - nbserverproxy

about:
  home: https://github.com/jupyterhub/nbserverproxy
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Jupyter server extension to proxy web services

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
    - lsetiawan
