{% set version = "0.8.8" %}

package:
  name: nbserverproxy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/n/nbserverproxy/nbserverproxy-{{ version }}.tar.gz
  sha256: 23558fa1efe42fa0a832a4e69eb9743e5b8724d95cc17ce38b5f8ede1d21020f

build:
  number: 1001
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - notebook

test:
  requires:
    - python {{ python_min }}
  imports:
    - nbserverproxy

about:
  home: https://github.com/jupyterhub/nbserverproxy
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Jupyter server extension to proxy web services

extra:
  recipe-maintainers:
    - minrk
    - ocefpaf
    - lsetiawan
