travis:
  secure:
    BINSTAR_TOKEN: suWbyrJwtHuU3E8aTPMLsRkHZUxopKqJJyPsadQ7anu4FPa25oYI0plFez/1ZqyIHzFdI9hS612/wfRVStucF47MoMCAN7P5knW5noBggBYnkxFoVnyupioWvFC/V5XJYmd+/Ws5Ua5SZOv5C+n9lTkFFWnOMbpbjWTeloGldv5d68qI6sHospSBvqfafNEpznp+j3OuzEYqpXocHAV4AehoOGfjnAxs787iv2VauzAwfhXEdMDJxzDt0344MUVEKDPaw405eYwiuENfPbYfciscBOBXcUqy+pmjlbowS39v6KGiK9puPLCZJDA/Lw2D0bGXZQEbz75fQJJMzfREGFPE4priGcO+Sn2V7M2O9iGQoWdw3fgpyimhOmeWQLqipqyjbfNhyoSdhle2G1umDTWfOcD9JU1hYRReqjyme0Is5e3H/KKRbCdItlxEbLzZgKuYMJYb0lH0vXp/UtLdaQuyLRMNSBbLp/XAFDwDDEpZuzo/jRbZuWmaZqw5CleqZQNTf1o7y2EYYNd6ccBGK2Z0YtEHYBQx12Bi4tZ/uSF53ZbaVh0AvFPhdtcHa/HdoG1whmDogiqw6Yv/bqzpHDU/HkC78xk8KG+/GfFoF3RLicS+XMH+XyreGozhBGuXUHF4tTVttVBb9GQYEGKxV2tvHtxeN3UmY/ZJjGNlUZE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
